# -*- coding: utf-8 -*-
"""Article_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hrTd_4CE9dr8aNNa9dwD2wu54asoTzT
"""

from google.colab import drive
drive.mount('/content/drive')

import requests
import re, re as regex
import time
import pandas as pd
import random
import nltk
from datetime import datetime
import ast
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Used for exporting .csv file to the Drive
import shutil
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

articles_all = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/MAP6114 - Machine Learning/MAP 6114 Project/FINAL_articles_raw.csv")

articles_raw = articles_all.drop(columns=['text', 'summary', 'meta'])

articles_raw['keywords'] = articles_raw['keywords'].apply(ast.literal_eval)

# Convert lists to tuples because tuples are hashable and fast to count
display(articles_raw['keywords'].apply(tuple).value_counts().head(20))

print(f'Prior to cleaning, the DF has {len(articles_raw)} articles')

names = ['msn', 'zerohedge', 'redirected']

for name in names:
  articles_raw = articles_raw[~articles_raw['keywords'].apply(lambda x: x == [name])]

articles_raw = articles_raw[~articles_raw['keywords'].apply(lambda x: x == [])]
articles_raw = articles_raw.reset_index(drop=True)

print(f'After cleaning, the DF has {len(articles_raw)} articles')

display(articles_raw)

articles_raw["date"] = pd.to_datetime(articles_raw["date"], format='mixed', utc=True)
articles_raw["date"] = articles_raw["date"].dt.tz_convert(None)

display(articles_raw)

#For ease of analysis set week to Monday
articles_raw["week_start"] = articles_raw["date"].dt.to_period("W-MON").dt.start_time
display(articles_raw[["date", "week_start"]].head())

display(articles_raw['keywords'].apply(tuple).value_counts().head(1000))

display(articles_raw['week_start'].value_counts())

all_articles_en = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/MAP6114 - Machine Learning/MAP 6114 Project/Model_Cheyanne/Uploads to Batch Processing/all_articles_en.csv")

all_articles_en.columns

# Removes duplicates of the articles within the same week (assuming they were updated)
all_articles_en_unique = all_articles_en.drop_duplicates(subset=['url', 'week_start', 'week_end'])

articles_raw_cleaned = articles_raw.drop_duplicates(subset='url', keep='first')
print(len(articles_raw))
print(len(articles_raw_cleaned))

articles_merged = articles_raw_cleaned.merge(all_articles_en_unique, on = 'url', how = 'left')

print(len(articles_merged) - len(articles_raw_cleaned))

duplicates = articles_merged['url'].value_counts()

print(len(duplicates[duplicates>1]))

"""There are 70 additional rows in the 'articles_merged' DF than in the 'articles_raw_cleaned' DF. This is because some articles were republished at later dates. For example, one article may be originally printed in February, but printed again in June. The assumption was made that the reprinted article continues to be relevant, thus both articles were kept within the dataset."""

display(articles_merged.columns)

articles_merged.dtypes

articles_merged['language'].unique()

display(articles_merged)

articles = articles_merged.drop(columns = ['title_x', 'date_x', 'week_start_x', 'week_end','date_y', 'domain', 'language'])
articles = articles.rename(columns = {'title_y': 'title', 'week_start_y': 'week_start'})

display(articles)

articles['week_start'].unique()

#  Set global export location - Used for all exports within the file unless explicitly overwritten.
destination_folder = '/content/drive/MyDrive/Colab Notebooks/MAP6114 - Machine Learning/MAP 6114 Project/Model_Cheyanne'

def save_and_export_to_drive(df, source_file_name, destination_folder_name):
  # Save file
  df.to_csv(source_file_name, index = False)

  # Export file to drive
  shutil.copy(source_file_name, destination_folder_name)

  # Returns file names in the destination folder as a Python SList
  # Format: ['file1.csv file2.csv'] - Files are not delimited by commas
  files = !ls "{destination_folder}"

  # Extract the file names and split on the space to format the file names as a list.
  all_filenames = files[0].split()
  print(all_filenames)

  # Verify that the file was copied to the destination folder.
  if source_file_name in all_filenames:
    print(f"'{source_file_name}' successfully copied to '{destination_folder}'")
  else:
    print(f"'{source_file_name}' not found in '{destination_folder}'")

save_and_export_to_drive(articles, 'articles.csv', destination_folder)